### ISSUE TITLE
Disable jacket layers on arms when not rendering

### ISSUE THREAD

**Issue by WolfieWaffle** [DonBruce64/RealFirstPersonRender#1] opened 2017-11-05 06:34 UTC
The second layer of arms still render in 3D whenever the rest of the arm is disabled (such as when holding a compass)

**Comment by DonBruce64** [comment] 2017-11-17 23:37
What is the second layer of arms?  It's not armor is it?

**Comment by WolfieWaffle** [comment] 2017-11-18 00:44
No, in some relatively recent version there is now 2 layers on all body parts, not just the head. It's like the second head skin layer but on arms and legs etc.

**Comment by DonBruce64** [comment] 2017-11-18 01:07
After some research it appears this change happened in 1.8+.  As 1.10.2 seems to be the de-facto standard above 1.10.2, I'll start with that version for this and the other changes.

**Comment by DonBruce64** [comment] 2017-11-18 01:21
Can you send me a screenshot of the issue on your player?  Testing shows that *armor* is still rendering, but from what I can tell the playermodel shouldn't be.  I can't test this on my end due to being defaulted to Steve in the dev environment.

**Comment by WolfieWaffle** [comment] 2017-11-18 04:42
I have a black ring on my skin's outer arm layer, which can be seen here:

![2017-11-17_21 38 37](https://user-images.githubusercontent.com/8770485/32976949-178e5358-cbe0-11e7-8e85-42d3d114cc19.png)

**Comment by DonBruce64** [comment] 2017-11-18 04:51
Odd, that should be fixed.  Would you be able to post your skin here?  I can force-inject it into Minecraft with some trickery to experiment with different versions to try and nail this down.

**Comment by WolfieWaffle** [comment] 2017-11-18 05:22
![wolfie_waffle](https://user-images.githubusercontent.com/8770485/32977204-cf01f530-cbe5-11e7-89ee-b1306cb6b11a.png)

**Comment by DonBruce64** [comment] 2017-11-18 05:46
![2017-11-17_23 42 14](https://user-images.githubusercontent.com/15241611/32977351-7ad48c1e-cbf1-11e7-8479-92ba5beb39bb.png)
Can confirm this is not an issue in 1.10.2.  Will push on to 1.11+ and see if it happens there.

**Comment by DonBruce64** [comment] 2017-11-18 06:17
Not an issue in 1.11.  Moving to 1.12 for testing.

**Comment by DonBruce64** [comment] 2017-11-18 06:35
![2017-11-18_00 30 15](https://user-images.githubusercontent.com/15241611/32977695-2deaffa8-cbf8-11e7-8420-fb1950bdeb4b.png)
Cannot reproduce in any MC version.  Have you tried running RFPR by itself?  This is starting to smell like a bad mod interaction.  @WolfieWaffle

**Comment by WolfieWaffle** [comment] 2017-11-18 15:13
![2017-11-18_08 12 14](https://user-images.githubusercontent.com/8770485/32981899-52105cda-cc38-11e7-99d2-975e5ecf4ff0.png)

1.12.2, this is the only mod installed, the one from the Curse page

**Comment by DonBruce64** [comment] 2017-11-18 15:24
Odd.  Not sure why I can't reproduce it on my end.  What version of Forge are you using?  Also, you're running the 1.11.2 mod on a 1.12.2 system, correct?  I don't think that's the issue, but I just want to confirm.

**Comment by WolfieWaffle** [comment] 2017-11-18 15:26
Version 1.1.3

**Comment by DonBruce64** [comment] 2017-11-18 15:30
1.1.3?  That sounds like a Forge Modloader version number.  Forge versions typically look like this "1.12 - 14.21.1.2387", where the last 4 digits are the version number.

**Comment by WolfieWaffle** [comment] 2017-11-18 19:56
Oh 1.1.3 was the version on Curse in the filename, the forge version is 14.23.0.2544

**Comment by DonBruce64** [comment] 2017-11-18 20:13
Okay, now I'm *really* confused here.  I downloaded the most recent version of RFPR I host on Curse and got this:
![image](https://user-images.githubusercontent.com/15241611/32984343-9bc31d90-cc6a-11e7-84f8-12b532ab84f5.png)
How are you running a 1.11 mod on 1.12?

**Comment by WolfieWaffle** [comment] 2017-11-19 00:36
I have no idea XD I guess that must be a problem though, I'll just wait for 1.12.2 version, didn't realize I was using a 1.11 mod.

**Comment by DonBruce64** [comment] 2017-11-19 00:47
[Real First-Person Render-1.12.2-8.1.0.zip](https://github.com/DonBruce64/RealFirstPersonRender/files/1485176/Real.First-Person.Render-1.12.2-8.1.0.zip)
Try this version.  I compiled it with Forge 1.12-14.21.1.2387 so it should behave on your end as well.

**Comment by WolfieWaffle** [comment] 2017-11-21 05:57
Yup it worked for me I think, didn't see the bug

**Comment by DonBruce64** [comment] 2017-11-21 15:14
Nice.  I'll mark this as once I push that release to the Curse site.  Would you be able to send me the version you were using?  I'm still confused as to how you got it to work on 1.12.  Did you not download from Curse?  The only way I could see that mod working on 1.12 is if someone compiled the code themselves on that version.  Just really confused as to how you got it working on your end even partially.

**Comment by DonBruce64** [comment] 2017-11-27 02:26
Officially closed due to lack of response.  Will re-open if followed up on.

**Comment by WolfieWaffle** [comment] 2017-11-27 02:33
Oh sorry, here is the jar that has the bug, I think it was from Curse

[realrender-1.1.3.zip](https://github.com/DonBruce64/RealFirstPersonRender/files/1504540/realrender-1.1.3.zip)

**Comment by DonBruce64** [comment] 2017-11-27 02:44
The jarfile you posted looks to be an *extremely* old version of my code that's been forked and updated to 1.12.  In fact, the package declaration is not mine.  Rather, it's `package kenijey.realrender;`.  I seem to recall this fellow asking for the source code to this mod a while back.  Looks like he made a fork and updated as he was tired of me waiting.
His mod is here:
https://minecraft.curseforge.com/projects/first-person-render
My mod is here:
https://minecraft.curseforge.com/projects/real-first-person-render

Re-submitting this issue on his GitHub, but will fix and update my code and release to close this.

**Closed by DonBruce64** 2017-11-27 02:44 UTC
Labels: bug

**Comment by WolfieWaffle** [comment] 2017-11-27 02:50
Ah OK, didn't realize there was 2 mods

**Comment by DonBruce64** [comment] 2017-11-27 02:52
Eh, no worries.  I didn't know either, so it's a learning experience for the both of us.  Glad to finally get this resolved, though.

**Comment by kenijey** [comment] 2017-12-09 08:52
i'm investigating it.

**Comment by kenijey** [comment] 2017-12-09 09:07
well, @WolfieWaffle can you download the latest version of [First Person Render](https://minecraft.curseforge.com/projects/first-person-render) and try to reproduce it?
