### ISSUE TITLE
Use filled_map instead of map

### ISSUE THREAD

**Issue by WolfieWaffle** [DonBruce64/RealFirstPersonRender#2] opened 2017-11-05 06:35 UTC
I assume you want to disable rendering when holding a map that will actually show the gui, which has the id filled_map not map

**Comment by DonBruce64** [comment] 2017-11-17 23:36
That is correct, however testing on 1.7.10 shows that a filled_map is actually coded as a map as far as the item name goes.  Which MC version are you having this issue on?

**Comment by WolfieWaffle** [comment] 2017-11-18 00:44
I most likely was using 1.12.2

**Comment by DonBruce64** [comment] 2017-11-18 01:16
Can confirm this is not a bug in 1.10.2.  Will investigate later versions.

**Comment by DonBruce64** [comment] 2017-11-18 06:26
![2017-11-18_00 20 13](https://user-images.githubusercontent.com/15241611/32977631-d41cafd6-cbf6-11e7-9a59-df9ab4ebd268.png)
Tested in 1.12.2 using current recommended Forge (2387).  Default string of "map" works as expected, while string of "filled_map" does not.  Empty maps render like normal items as expected.  Closing as unable to reproduce on any modern version.

**Closed** 2017-11-18 06:26 UTC
Labels: bug
